//! Embeds the application icon (and basic file metadata) into the exe.
use std::env;
use std::path::Path;

fn main() {
    if env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        println!("cargo:rerun-if-changed=assets/mousetrails.ico");
        let mut res = winresource::WindowsResource::new();
        res.set("FileDescription", "MouseTrails — Windows Plus! style cursor effects");
        res.set("ProductName", "MouseTrails");
        if Path::new("assets/mousetrails.ico").exists() {
            res.set_icon("assets/mousetrails.ico");
        } else {
            // The icon is generated by `cargo run --example make_icon`; build
            // without it rather than failing the whole compile.
            println!(
                "cargo:warning=assets/mousetrails.ico not found — run `cargo run --release --example make_icon` to generate it"
            );
        }
        if let Err(e) = res.compile() {
            panic!("failed to compile Windows resources: {e}");
        }
    }
}
